[[rule]]
tags = ["js", "css"]
include = ["*.js", "*.css", "*.vue"]
command = ["prettier", "--stdin-filepath", "$file"]

[[rule]]
tags = ["python"]
include = ["*.py"]
command = ["fmt-ruff-with-includes", "--stdin-filename", "$file", "-"]

[[rule]]
tags = ["terraform"]
include = ["*.tf"]
command = ["terraform", "fmt", "-no-color", "-"]

[[rule]]
tags = ["go"]
include = ["*.go"]
command = ["gofmt"]

[[rule]]
noop = true
include = ["*.sublime-settings"]
